### ISSUE TITLE
Add name/desciption/icon to about:addons

### ISSUE THREAD

**Issue by pdehaan** [mozilla/shield-cloudstorage#20]
I'm on the [**cloud-storage-web-ext**](https://github.com/mozilla/shield-cloudstorage/tree/cloud-storage-web-ext) branch, and my about:addons page looks like this:

![add-ons_manager_-_main](https://user-images.githubusercontent.com/557895/39022032-8752f5d8-43e8-11e8-8463-b4f7ec5f232d.png)

Clicking the "More" link, gives me the following details view:

![add-ons_manager_-_details](https://user-images.githubusercontent.com/557895/39022052-9c23f82c-43e8-11e8-9ecd-28fa87af673b.png)

**Comment by punamdahiya** [comment]
Thanks @pdehaan for the fixes! Will reach out to UX for logo and take a stab at description. @gregglind please recommend if we need  update_url for shield web extensions.

**Comment by pdehaan** [comment]
Oh sorry. I thought this was a TestPilot experiment. Yeah, we can probably lose the update url.
