### ISSUE TITLE
The buttons background are wrongly displayed in the "Cloud Storage" notification on Windows and Ubuntu

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/shield-cloudstorage#26]
**[Affected versions]:**
- Latest Firefox Beta 60.0b15

**[Affected Platforms]:**
- All Windows
- All Linux

**[Prerequisites]:**
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have Dropbox/Google Drive installed on your computer:
	- Dropbox Cloud  https://www.dropbox.com/install
	- Google Drive  https://www.google.com/drive/download/
- Have the CloudStorage add-on installed.

**[Steps to reproduce]:**
1. Start the browser with the profile from prerequisites and navigate to: https://www.mozilla.org/en-US/firefox/all/ page.
2. Click any of the "Download" button from the page.
3. Click the "Save" button.
4. Click the download button from the browser toolbar.
5. Observe the "Not Now" and "Save to CloudStorage" buttons in the "CloudStorage" notification.

**[Expected result]:**
- The "Not Now" button has a gray background color.
- The "Save to CloudStorage" button has a blue background color.

**[Actual result]:**
- The "Not Now" button has a transparent background color.
- The "Save to CloudStorage" button has a transparent background color.

**[Notes]:**
- The issue is not reproducible on Mac 10.13.
- The buttons background are also wrong for the "Hover" and "Selected" states.
- Attached screenshots of the issue:
![cloudstorageui_windows](https://user-images.githubusercontent.com/20083658/39249323-14a7056a-48a7-11e8-9e66-a29f024adbe0.jpg)
![cloudstorageui_ubuntu](https://user-images.githubusercontent.com/20083658/39249328-18268828-48a7-11e8-9313-af9449ecbf15.jpg)

**Comment by punamdahiya** [comment]
@SoftVision-EmilPasca submitted fix, please test now. Thanks!

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible with the latest CloudStorage add-on installed (v1.0.0-04.26.2018), tested this on Windows 10 x64 and Ubuntu 14.04 with the latest Beta(60.0b15-20180423171039).
