### ISSUE TITLE
The "Save to Dropbox" option is wrongly selected by default when two providers are available after the browser is restarted

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/shield-cloudstorage#27]
[Notes]:
- In certain cases the issue is reproducible without restarting the browser. The "Save to Dropbox" option is selected by default when the notification is displayed for the first time.
- Even if the "Save to Dropbox" is selected the "Save to Cloud Storage" button is displayed and it's greyed out.

[Affected versions]:
- Dev Edition 60.b15

[Affected Platforms]:
- Windows 7 x64
- Windows 10 x64
- Mac 10.13

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the CloudStorage add-on installed.
- Have the Google Drive and Dropbox providers installed on you computer.

[Steps to reproduce]:
1. Start the Dev Edition browser with the profile from prerequisites and navigate to "https://www.mozilla.org/en-US/firefox/all/" page.
2. Click any of the "Download" button from the page.
3. Click the "Save" button.
4. Click the download button from the browser toolbar (if needed).
5. Observe the Cloud Storage notification.
6. Restart the browser from the developer toolbar using the "restart" command (Shift+F2/Fn+Shift+F2).
7. Download another file and click the download button from the browser toolbar.
8. Observe the Cloud Storage notification.

[Expected result]:
Step 5 & Step 8:  No option is selected by default

[Actual result]:
Step 5. No option is selected by default.
Step 8. The "Save to Dropbox" option is selected by default.

[Additional Notes]:
- Here is a screenshot with browser console when the issue is reproducible:
![web console when the issue is reproducible](https://user-images.githubusercontent.com/19226534/39353884-a02575c0-4a11-11e8-982a-b87ae1484148.png)

- Here is a screenshot with browser console when the issue is not reproducible: 
![browser console when the issue is not reporducible](https://user-images.githubusercontent.com/19226534/39353888-a254fe6a-4a11-11e8-9d84-010f6c68e6cf.png)

- Here is a screen recording with the issue:
![dropbox option set after restart](https://user-images.githubusercontent.com/19226534/39353910-adc5e0fc-4a11-11e8-96ec-0ea466105353.gif)

**Comment by punamdahiya** [comment]
@gijsk Subsequent restart of Firefox instance with extension installed shows first radio option selected by default in radio group 'multiProviderSelect' even though showNotification creates radio option afresh and doesn't mark any option explicitly checked.  Do you know what could be causing this? Thanks

https://github.com/mozilla/shield-cloudstorage/blob/cloud-storage-web-ext/webextension/privileged/ui/CloudDownloadsView.jsm#L343

**Comment by gijsk** [comment]
I don't know. The screencast is confusing because it's a gif so I can't easily stop it and it autoloops, but it looks like the second time we don't automatically open the dropdown (but we do the first time) - there's a click in the screencast. It's possible this causes focus changes which select one of the radio items because focus moves into the popup, whereas it doesn't do that when it auto-opens (the first time).

Does this reproduce if you close and reopen Firefox normally (without the 'restart'/devtools stuff) ? Am I right that the notification doesn't open automatically the second time (if so, why is that?).

**Comment by gijsk** [comment]
I hadn't noticed this when reviewing, but note that the enabled state of the button should be governed by whether a radio button is selected, and to do that you should probably use 'input' or 'change' events rather than 'click' ones. Also, to find the selected item you should be able to use the `value` property of the radiogroup.

**Comment by SoftVision-CosminMuntean** [comment]
> Does this reproduce if you close and reopen Firefox normally (without the 'restart'/devtools stuff) ? Am I right that the notification doesn't open automatically the second time (if so, why is that?).

The issue is also reproducible if I close the browser by using the "Exit" option from the "Australis" menu or if I close the browser by clicking the "X" button.
Yes, it seems that the download panel is not automatically opened the second time. 
Here is a ".mp4 " screen recording of the issue:  https://goo.gl/pxjYyb

**Comment by gijsk** [comment]
I guess we might want to mark the radio buttons disabled and enable them 1 tick (requestAnimationFrame) after the `popuppositioned` event? Then the code that autofocuses the first item in the popup will focus the first download, as expected.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue using the latest Cloud Storage (1.0.0) version and the issue is no longer reproducible. Tested with Firefox 60 unbranded build, Dev Edition 61.0b3 and latest Nightly (62.0a2) build on Windows 7 x64, 10 x64 and Mac 10.12.
