### ISSUE TITLE
"Not Now" and "Save to [provider_name]" buttons cannot be accessed on Mac OS using the keyboard

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/shield-cloudstorage#30]
[Affected versions]:
- Dev Edition 60.b16

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the CloudStorage add-on installed.
- Have the Google Drive and Dropbox providers installed on you computer.

[Steps to reproduce]:
1. Start the Dev Edition browser with the profile from prerequisites and navigate to "https://www.mozilla.org/en-US/firefox/all/" page.
2. Click any of the "Download" button from the page.
3. Click the "Save" button.
4. Click the download button from the browser toolbar (if needed).
5. Press the "Tab" key until the "Not Now" or "Save to [provider_name]" is focused.
6. Press the "Enter" key and observe the behavior.

[Expected result]:
- The focused button is actioned.

[Actual result]:
- Nothing happens.

[Notes]:
- I am not sure if the issue is also reproducible on Mac or Linux since the buttons cannot be focused using the keyboard (issue #29).
- The issue is not reproducible for the "Preferences" button.
- Here is a screen recording with the issue: https://goo.gl/nymPMG

**Comment by punamdahiya** [comment]
@SoftVision-CosminMuntean On Mac please confirm if you can access button using keyboard by pressing space bar. Thanks!

**Comment by SoftVision-CosminMuntean** [comment]
@punamdahiya yes, it seems that the buttons can be accessed if I'm using the spacebar.

**Comment by punamdahiya** [comment]
@SoftVision-CosminMuntean Thanks for validating, this should resolve keyboard access issue logged here. We are currently listening to command event for buttons, which means when focused element is selected (on Mac by pressing space bar).

On Mac, Handling buttons on Return keypress in addition to space bar, can be logged as separate issue and fixed if deemed necessary for study. Thanks!

**Comment by SoftVision-EmilPasca** [comment]
> On Mac, Handling buttons on Return keypress in addition to space bar, can be logged as separate issue and fixed if deemed necessary for study. Thanks!

@punamdahiya,  I've filled the issue here: https://github.com/mozilla/shield-cloudstorage/issues/33
