### ISSUE TITLE
The files are wrongly downloaded in the local folder if the Dropbox download location is changed while the browser is opened 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/shield-cloudstorage#32]
[Additional Notes]:
- The files are downloaded in the local folder until the browser is restarted. After this, the files are correctly downloaded in the newly set location for Dropbox folder.

[Affected versions]:
- Fifox 60 unbranded build
- Dev Edition 61.0b3
- Nightly 62.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Cloud Storage add-on installed.
- Have Dropbox providers installed on you computer.
- Have the "Save to Dropbox" option already set.

[Steps to reproduce]:
1. Start the Firefox browser with the profile from prerequisites.
2. Change the location of the Dropbox download folder.
3. Focus the browser and navigate to "https://www.mozilla.org/en-US/firefox/all/" page
4. Download any file and click the "Download" icon from browser toolbar.
5. Observe the downloaded file.

[Expected result]:
- The file is downloaded in the Dropbox new location.

[Actual result]:
- The file is downloaded in the local download location.

[Notes]:
- Here is a screen recording with the issue: https://goo.gl/GfoziW

**Comment by punamdahiya** [comment]
@SoftVision-CosminMuntean This is a known issue, CloudStorage API scans for provider metadata at the start of Firefox instance. 
In the rare circumstances when the user changes Dropbox download folder location right after opt-in (click of save to Dropbox) and before restart, getDownloadFolder  return system default download in the absence of a valid metadata.
