### ISSUE TITLE
"Not Now" and "Save to [provider_name]" buttons cannot be accessed using the "Enter" key on Mac OS

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/shield-cloudstorage#33]
[Affected versions]:
- Dev Edition 60.b16

[Affected Platforms]:
- All Mac

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the CloudStorage add-on installed.
- Have the Google Drive and Dropbox providers installed on you computer.

[Steps to reproduce]:
1. Start the Dev Edition browser with the profile from prerequisites and navigate to "https://www.mozilla.org/en-US/firefox/all/" page.
2. Click any of the "Download" button from the page.
3. Click the "Save" button.
4. Click the download button from the browser toolbar (if needed).
5. Press the "Tab" key until the "Not Now" or "Save to [provider_name]" is focused.
6. Press the "Return" key and observe the behavior.

[Expected result]:
- The focused button is actioned.

[Actual result]:
- Nothing happens.

[Notes]:
- The buttons can be actionated using the "Spacebar" key.
- Here is a screen recording with the issue: 

![macosenterkey](https://user-images.githubusercontent.com/20083658/39928072-056eebb0-553d-11e8-9d09-3a281163453f.gif)

**Comment by punamdahiya** [comment]
Buttons are accessible via keyboard using Mac default selection using "spacebar" key, labeling issue stretch and to be fixed only if deemed necessary for study
