### ISSUE TITLE
Files downloaded through File Sharing websites are not correctly updated in the Download panel, when moved into another provider location

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/shield-cloudstorage#34]
[Affected versions]:
- Firefox 60.0 unbranded build
- Dev Edition 61.0b5
- Nightly 62.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the CloudStorage add-on installed.
- Have the Google Drive or Dropbox providers installed on you computer.
- Have a file uploaded through "[Firefox Send](https://send.firefox.com/)" or "[mega.nz](https://mega.nz/)" websites.

[Steps to reproduce]:
1. Start the Dev Edition browser with the profile from prerequisites and navigate to the https://goo.gl/8Wobi2 page.
2. Download the file and click the download button from browser toolbar.
3. Right click on the downloaded file.
4. Click the "Move Download To..." option and select any provider. 
5. Observe the downloaded file.

[Expected result]:
The downloaded file is correctly moved to the selected provider and it is displayed once.

[Actual result]:
The file is duplicated: 
- The first displayed is moved to the selected provider folder but the "File moved or missing" message is displayed under it.
- The second displayed is downloaded to the local folder.

[Notes]:
- If the Downloaded panel is closed and reopened, the two files correctly update their status messages (the first one has the download time and the second one has the "File moved or missing" message)
- Here is a screen recording with the issue: https://goo.gl/rE5PyB

**Comment by punamdahiya** [comment]
@SoftVision-CosminMuntean Thanks for catching this issue. It's a fallout of failure to setPageAnnotation with blob source URL . See https://bugzilla.mozilla.org/show_bug.cgi?id=1298362

I have landed the fix with #28 PR by explicitly catching error in try catch while moving download. Please verify. Thanks!

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using latest Cloud Storage (1.0.0) build  and is no longer reproducible. Tested using Firefox 60 Unbranded build, Beta 61.0b6 on Windows 7 x64, Mac 10.13 and Ubuntu 16.04.
