### ISSUE TITLE
The Cloud Storage notification no long appears if the "cloud.services.storage.key" pref is reset 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/shield-cloudstorage#35]
[Affected versions]:
- Firefox 60.0 unbranded build
- Dev Edition 61.0b6
- Nightly 62.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the CloudStorage add-on installed.
- Have the Google Drive or Dropbox providers installed on you computer.

[Steps to reproduce]:
1. Start the Dev Edition browser with the profile from prerequisites and navigate to the https://www.thinkbroadband.com/download page.
2. Download the "5 Mb" file and click the download button from browser toolbar.
3. Choose one of the available providers and click the "Save files to [provider_name]".
4. Navigate to "about:config" page and search for the "cloud.services.storage.key" pref.
5. Right click on the pref and choose the "Reset" option.
6. Navigate to https://www.thinkbroadband.com/download page.
7. Download any file and click the download button from browser toolbar.
5. Observe Download panel.

[Expected result]:
- The Cloud Storage notification is displayed.

[Actual result]:
- The Cloud Storage notification is not displayed.

[Notes]:
- Even if the notification is not displayed, the "Move Download To ..." option is displayed.
- If I set the "cloud.services.interval.prompt" pref to "0" the notification is correctly displayed.	 	
- The issue is still reproducible after the browser is restarted.
- Here is a screen recording with the issue: https://goo.gl/rg8bRz

**Comment by punamdahiya** [comment]
It's expected behavior. cloud.services.interval.prompt (in days) decides when the prompt is next shown after the last prompt shown. 
After opt-in  even if you have reset the pref, notification will still be shown after the interval. Thanks!
