### ISSUE TITLE
The "provider" and "provider_count" parameters are not collected after the "Not Now" button is pressed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/shield-cloudstorage#36]
[Affected versions]:
- Firefox 60.0 unbranded build
- Dev Edition 61.0b6
- Nightly 62.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the CloudStorage add-on installed.
- Have the Google Drive and Dropbox providers installed on you computer.

[Steps to reproduce]:
1. Start the Dev Edition browser with the profile from prerequisites and navigate to the https://www.thinkbroadband.com/download page.
2. Download the "5 Mb" file and click the download button from browser toolbar.
3. Click the "Not Now" button.
4. Navigate to "about:telemetry" page and switch to "Archive ping data".
5. Select the most recent sent ping.
6. Click the "Raw Playload" tab and observe the conent.

[Expected result]:
- All the information is correctly displayed.

[Actual result]:
- The "provider" parameter doesn't display any information and the "provider_count" parameter is missing.

[Notes]:
- Even if you have one or two providers installed the parameters are missing.
- Here is a screen recording with the issue: https://goo.gl/B9GWfZ

**Comment by punamdahiya** [comment]
Click of cancel dismisses notification and user can do do without selecting a provider. Updating telemetry to include provider_count and remove provider key which is not needed here. Please verify. Thanks!

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using latest Cloud Storage build and the issue is no longer reproducible.  The "provider_count" parameter is correctly displayed and the provider key is removed.
