### ISSUE TITLE
The "enter" and "installed" pings are wrongly sent whenever re-enabling the addon

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/shield-cloudstorage#41]
[Affected versions]:
- Firefox Unbranded 60.0

[Affected Platforms]:
- All Mac
- All Windows

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set to "true".
- Have the CloudStorage add-on installed.
- Have the Google Drive and Dropbox providers installed on your computer.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and navigate to "about:addons" page.
2. Disable/Enable the "CloudStorage" addon multiple times.
3. Observe the ping data in "about:telemetry#raw-payload-tab".

[Expected result]:
- Only one ping entry of the "enter" and "installed" study states are displayed.

[Actual result]:
- Multiple pings entries of the "enter" and "installed" study states are displayed.

[Notes]:
- This is also reproducible for the "addon_init" ping data.
- Here is a screen recording of the issue: 
![enterstudystate](https://user-images.githubusercontent.com/20083658/40543679-21e1b718-602e-11e8-86fd-942a3e51f530.gif)

**Comment by SoftVision-EmilPasca** [comment]
I have verified this issue with the latest version and the following "study_state" telemetry probes are sent when disabling/enabling the addon:
"user-disable","exit","enter" and "installed".

Is this the intended behaviour?

**Note:**
- Attached a screen-recording of the above behavior:
![cloud_storage](https://user-images.githubusercontent.com/20083658/41602012-843e3db0-73e2-11e8-8c06-7d632abdad75.gif)

**Comment by punamdahiya** [comment]
@SoftVision-EmilPasca Shield-Utils v5 not supporting user disable and user uninstall  is known issue. Telemetry pings 'exit', 'enter' and 'installed' are coming from shield-utils. 

@motin @gregglind  please let me know if this issue should be logged against shield-utils v5 or if there is an issue already existing we can mark it as duplicate. Thanks!

**Comment by motin** [comment]
@punamdahiya I believe this is expected behavior, but please do file an issue against the utils repo to get an official statement regarding this.

**Comment by gregglind** [comment]
User disable should send pings “user disable” and “exit” but will not open
the survey.

We are deciding how we want to default that case,  but currently this is a
known wontfix.
