### ISSUE TITLE
The "download_started" ping is wrongly sent twice if the Cloud Storage is removed then reinstalled

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/shield-cloudstorage#42]
[Affected versions]:
- Firefox 60.0 unbranded build
- Dev Edition 61.0b6
- Nightly 62.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the CloudStorage add-on installed.
- Have the Google Drive or Dropbox providers installed on you computer.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and navigate to "about:addons" page.
2. Remove the Cloud Storage add-on and refresh the page.
3. Reinstall the Cloud Storage add-on.
4. Navigate to the https://www.thinkbroadband.com/download page.
5. Download the "5 Mb" file and click the download button from browser toolbar..
6. Navigate to "about:telemetry" page and switch to "Archive ping data".
7. Observe the last sent pings.

[Expected result]:
- The "download_started" ping is sent only one time.

[Actual result]:
- The "download_started" ping is sent twice.

[Notes]:
- The issue is no longer reproducible if you restart the browser after reinstalling the add-on.
- Here is a screen recording with the issue: https://goo.gl/16FHzJ

**Comment by punamdahiya** [comment]
Clarified with Cosmin, the issue is seen with code in PR https://github.com/mozilla/shield-cloudstorage/pull/38 and not on master.

Uninstall and disable flow that handles removing listeners is not yet functional in PR  (See https://github.com/mozilla/shield-cloudstorage/pull/38#issuecomment-391178143) which could be the reason for this bug.

Labeling it as v5 dependency issue

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using latest Cloud Storage version (v5) on Firefox 60 and the issue is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Ubuntu 16.04 x64.
