### ISSUE TITLE
baseUrl -> baseUrls

### ISSUE THREAD

**Issue by motin** [mozilla/shield-cloudstorage#44]
Just noticed this discrepancy: baseUrl should be baseUrls where endings are defined, or else survey's won't be opened by the study utils. See https://github.com/mozilla/shield-cloudstorage/blob/master/webextension/studySetup.js#L38 and https://github.com/mozilla/shield-cloudstorage/blob/master/webextension/studySetup.js#L44

**Comment by punamdahiya** [comment]
Thanks for noticing, updated master with the fix
