### ISSUE TITLE
The "existing_cloud_provider_download_setting" ping is not sent if you already have the default download set to a cloud provider folder

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/shield-cloudstorage#47]
[Affected versions]:
- Firefox 60.0.2 (Unbranded build)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the "Save files to" option set to "Dropbox" or "Google Drive" downlod folder.

[Steps to reproduce]:
1. Start the Firefox browser with the profile from prerequisites.
2. Install the latest Cloud Storage (v5) version.
3. Navigate to "https://www.mozilla.org/en-US/firefox/all/" page.
4. Download any file and navigate to "about:telemetry" page. 
5. Switch to "Archive ping data".
6 .Click the "Raw Playload" tab and observe the latest pings sent.

[Expected result]:
- The "existing_cloud_provider_download_setting" ping is sent.

[Actual result]:
- There is no "existing_cloud_provider_download_setting" ping sent.

[Notes]:
- Based on the "[Cloud Storage Shield Study Phase 2 Instrumentation](https://docs.google.com/document/d/17Mmo48BDpd4uBIpA82B0D6LUSMXwvKczS_2I4yI8JaU/edit)" doc, the ping is sent when user has existing (before opt-in from cloud storage notification) default download setting as cloud provider folder.
- The following pings are send: "enter", "installed", "addon_init" and "download_started".
- Here is a screen recording of the issue: https://goo.gl/9rHjCg

**Comment by punamdahiya** [comment]
@SoftVision-CosminMuntean Thanks for logging this issue, here are my findings:

Debugging the issue during install getDownloadFolder call on CloudStorage back-end API is triggered before back-end  API has initialized (probably a race condition)
https://github.com/mozilla/shield-cloudstorage/blob/master/webextension/privileged/ui/CloudDownloadsView.jsm#L235

I was able to see in browser logs below message when this happens
CloudStorage: Failed to initialize and retrieve download folder   CloudStorage.jsm:476
	getDownloadFolder resource://gre/modules/CloudStorage.jsm:476:9

Subsequent restart of browser after addon install resolves this issue and logs both addon_init ping and existing_cloud_provider_download_setting ping correct.

Considering this is a edge case
a) Happens only for users who have set their download settings manually to cloud provider folder before add-on install
b) Seen one time on install of add-on and not replicable for addon_init ping on subsequent restart of browser

My take this will be a very small percentage of users and should not be a blocker. Thanks
