### ISSUE TITLE
The Cloud Storage prefs are not reset after the study expires

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/shield-cloudstorage#49]
[Affected versions]:
- Firefox 60.0.2 (Unbranded build)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".

[Steps to reproduce]:
1. Start the Firefox browser with the profile from prerequisites.
2. Install the latest Cloud Storage (v5.0.2) version.
3. Navigate to "https://www.mozilla.org/en-US/firefox/all/" page and download any file.
4. From the Cloud Storage notificaion select the "Dropbox" provider.
5. Click the "Save to Dropbox" button.
6. Change the system date in the future to "07/09/2018".
7. Restart the browser and observe the behavior.
8. Navigate to "about:config" page and search for the "cloud.services.storage.key" pref.

[Expected result]:
Step 7: The Cloud Storage survey is launched and the experiment is removed.
Step 8. The pref is reset or does not exist.

[Actual result]:
Step 7: The Cloud Storage survey is launched and the experiment is removed.
Step 8. The pref is still set to "Dropbox".

[Notes]:
- Unfortunately I can't make a screen recording since I have to change the system date in the future.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest Cloud Storage v5.0.2 version and it is no longer reproducible. Tested on Mac 10.13, Windows 7 x64, and Ubuntu 16.04 x64.

**Comment by gregglind** [comment]
Awesome, thanks!
