### ISSUE TITLE
The "addon_init" and "download_started" pings are wrongly sent twice after the browser was restarted or updated 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/shield-cloudstorage#51]
[Affected versions]:
- Firefox 60.0.2
- Firefox 61.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Google Drive or Dropbox providers installed on you computer.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and install the latest Cloud Storage version (5.0.2).
2. Restart the browser.
3. Navigate to the https://www.thinkbroadband.com/download page.
4. Download the "5 Mb" file.
5. Navigate to "about:telemetry" page and switch to "Archive ping data".
6. Observe the last sent pings.

[Expected result]:
- The "addon_init" and "download_started" pings are sent only one time.

[Actual result]:
- The "addon_init" and "download_started" pings are sent twice.

[Notes]:
- The issue is also reproducible if you remove and reinstall the extension. We had a similar issue on Cloud Storage v5.0.0 (see #42).
- Here is a screen recording with the issue: https://goo.gl/G2kA5P

**Comment by gregglind** [comment]
Thank you for catching this.

I suggest this can be solved during analysis.

**Comment by punamdahiya** [comment]
Thanks for logging, I guess it was missed because it was seen only for these two pings on browser restart. It will be a good bug to fix and have submitted PR

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using latest Cloud Storage version and the issue is no longer reproducible.  Tested on Windows 7 x64, Mac 10.13 and Ubuntu 16.04 x64.
