### ISSUE TITLE
Integrate Shield Utils API

### ISSUE THREAD

**Issue by punamdahiya** [mozilla/shield-cloudstorage#7]
Cloud Storage web extension shield utils support
Integrate 
Shield Utils API integration to support
- study duration
- study variations
- post survey at the end of study
- telemetry

Dependency on Shield Utils API in dev
https://github.com/mozilla/shield-studies-addon-utils/pull/120
https://github.com/motin/shield-studies-addon-utils/tree/v5-init/test-addon

**Comment by motin** [comment]
Quick update: PR mozilla/shield-studies-addon-utils#120 is merged and the new PR to depend on is https://github.com/mozilla/shield-studies-addon-utils/pull/135
The relevant example add-on for reference will be https://github.com/mozilla/shield-studies-addon-utils/tree/121-finalize-schema/examples/small-study
The API and the small-study example is still changing a lot this week, so hold off a bit more before integrating the new utils API.

**Comment by motin** [comment]
Tracking issue for the implementation of the proposed v5 API: https://github.com/mozilla/shield-studies-addon-utils/issues/160

**Comment by motin** [comment]
Tracking issue specifically for what is required for this study: https://github.com/mozilla/shield-studies-addon-utils/issues/173
